[tool.uv.workspace]
members = ["python"]

[tool.uv.sources]
hyper = { workspace = true }

[dependency-groups]
dev = [
    "hyper[content]",
    "pytest>=9.0.1",
    "pytest-cov>=7.0.0",
    "msgspec>=0.20",
    "pydantic>=2.12",
]

[tool.ruff.lint.per-file-ignores]
"playground/**" = ["F821"]
